name: "another"

on: [ push ]

jobs:
  another:
    name: another
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
        with:
          path: test-publish
      - name: test
        run: |
          git clone --depth 1 https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/VidarHUN/test-another.git
          cd test-another
          echo "test" >> README.md
          git add .
          git commi -m "test"
          git push
