name: "release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: versioning
        run: npm version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - name: commit changes
        run: |
          git config --global user.email "github_robot@github.com"
          git config --global user.name "Github Robot"
          git add .
          git commit -m "Update package version from github"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: publish    
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
  push_to_registry:
    name: push docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag vidarhun/test-publish:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push vidarhun/test-publish:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag vidarhun/test-publish:latest
      - name: Push the latest Docker image
        run: docker push vidarhun/test-publish:latest
