name: "release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: versioning
        run: npm version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - name: Commit changes
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          push-branch: master
          commit-message: "Update package version"
          add: "*.json"
      - name: publish    
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
